import random


# Function to draw a circle
def draw_circle():
    circle_art = """
       ____  
     /      \ 
    |        | 
     \ ____ /  
    """
    print(circle_art)


# Function to draw a set of lines based on user input
def draw_lines():
    try:
        # Input for the number of lines
        num_lines = int(input("How many lines would you like to draw? "))

        # Input for the character(s) to repeat
        char = input("What character(s) would you like to repeat? ")

        # Input for the number of times the character(s) should be repeated
        repeat_count = int(input("How many times would you like to repeat the character(s)? "))

        # Print the lines
        for i in range(num_lines):
            print(char * repeat_count)

    except ValueError:
        print("Invalid input. Please enter valid numbers for the line count and repetition.")


# Function to generate a random design
def random_design():

    design_num = random.randint(1, 3)
    if design_num == 1:

        # I know how to make ASCII letter and created my name

        print("""
              _       _            
             | | __ _| | ___ _ __  
          _  | |/ _` | |/ _ \ '_ \ 
         | |_| | (_| | |  __/ | | |
          \___/ \__,_|_|\___|_| |_|
          
        """)
    elif design_num == 2:

        # I accidentally created this design in an attempt to create something else
        # But I kept it because it looks like snowflakes falling from the sky

        SENTINEL = 20
        count = 0
        while count != SENTINEL:
            print(("*" * random.randint(1,3), " " * random.randint(1,4))*10)
            count +=1
    else:
        #This code was generated by AI to create a pyramid
        for i in range(10):
            # Print leading spaces to center the pyramid
            print(" " * (10 - i - 1), end="")

            # Print the "#" characters for this row (2*i + 1 ensures odd number of #)
            print("#" * (2 * i + 1))


# Main menu function
def make_a_choice():
    print("\nChoose an option:")
    print("1. Output a circle")
    print("2. Output a set of lines")
    print("3. Output a random design")
    print("4. Exit")

    try:
        choice = int(input("Enter your choice (1, 2, 3, or 4): "))
        return choice
    except ValueError:
        print("Invalid input. Please enter a number between 1 and 4.")
        return None


def main():
    choice = make_a_choice()  # Get the user's choice before entering the loop
    SENTINEL = 4

    while choice != SENTINEL:
        if choice == 1:
            draw_circle()
        elif choice == 2:
            draw_lines()
        elif choice == 3:
            random_design()
        elif choice == SENTINEL:
            break  # This is to exit the loop
        else:
            print("Invalid choice. Please enter 1, 2, 3, or 4.")

        # Ask for the user's choice again
        choice = make_a_choice()

    print("Hope you enjoyed!")


# Run the menu function to start the program
main()
